### ISSUE TITLE
Error in fixture: "../app/code/Magento/InventoryApi/Test/_files/source_items.php

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1378]
### Preconditions
1. Magento MSI

### Steps to reproduce
1. Run api-functional test app/code/Magento/InventorySourceSelectionApi/Test/Api/SourceSelectionServiceTest

### Expected result
1. DB query is correct and executes without error
```mysql
DELETE FROM `inventory_stock_10` WHERE (sku IN ('SKU-1', 'SKU-3', 'SKU-4'))
```

### Actual result
1. PHPUnit\Framework\Exception.
```
Error in fixture: "\/var\/www\/html\/msi\/dev\/tests\/integration\/testsuite\/..\/..\/..\/..\/app\/code\/Magento\/InventoryApi\/Test\/_files\/source_items.php".
 SQLSTATE[HY000]: General error: 1412 Table definition has changed, please retry transaction, query was: DELETE FROM `inventory_stock_10` WHERE (sku IN ('SKU-1', 'SKU-3', 'SKU-4'))
 #0 /var/www/html/msi/lib/internal/Magento/Framework/DB/Statement/Pdo/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#1 /var/www/html/msi/vendor/magento/zendframework1/library/Zend/Db/Statement.php(303): Magento\Framework\DB\Statement\Pdo\Mysql->_execute(Array)
#2 /var/www/html/msi/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 /var/www/html/msi/vendor/magento/zendframework1/library/Zend/Db/Adapter/Pdo/Abstract.php(238): Zend_Db_Adapter_Abstract->query('DELETE FROM `in...', Array)
#4 /var/www/html/msi/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(540): Zend_Db_Adapter_Pdo_Abstract->query('DELETE FROM `in...', Array)
#5 /var/www/html/msi/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(614): Magento\Framework\DB\Adapter\Pdo\Mysql->_query('DELETE FROM `in...', Array)
#6 /var/www/html/msi/vendor/magento/zendframework1/library/Zend/Db/Adapter/Abstract.php(664): Magento\Framework\DB\Adapter\Pdo\Mysql->query('DELETE FROM `in...')
#7 /var/www/html/msi/app/code/Magento/InventoryIndexer/Indexer/IndexHandler.php(80): Zend_Db_Adapter_Abstract->delete('inventory_stock...', '(sku IN ('SKU-1...')
#8 /var/www/html/msi/app/code/Magento/InventoryIndexer/Indexer/SourceItem/SourceItemIndexer.php(136): Magento\InventoryIndexer\Indexer\IndexHandler->cleanIndex(Object(Magento\InventoryMultiDimensionalIndexerApi\Model\IndexName), Object(ArrayIterator), 'default')
#9 /var/www/html/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\InventoryIndexer\Indexer\SourceItem\SourceItemIndexer->executeList(Array)
#10 /var/www/html/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\InventoryIndexer\Indexer\SourceItem\SourceItemIndexer\Interceptor->___callParent('executeList', Array)
#11 /var/www/html/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\InventoryIndexer\Indexer\SourceItem\SourceItemIndexer\Interceptor->Magento\Framework\Interception\{closure}(Array)
#12 /var/www/html/msi/generated/code/Magento/InventoryIndexer/Indexer/SourceItem/SourceItemIndexer/Interceptor.php(52): Magento\InventoryIndexer\Indexer\SourceItem\SourceItemIndexer\Interceptor->___callPlugins('executeList', Array, Array)
#13 /var/www/html/msi/app/code/Magento/InventoryIndexer/Plugin/InventoryApi/ReindexAfterSourceItemsSavePlugin.php(54): Magento\InventoryIndexer\Indexer\SourceItem\SourceItemIndexer\Interceptor->executeList(Array)
#14 /var/www/html/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(146): Magento\InventoryIndexer\Plugin\InventoryApi\ReindexAfterSourceItemsSavePlugin->afterExecute(Object(Magento\Inventory\Model\SourceItem\Command\SourceItemsSave\Interceptor), NULL, Array)
#15 /var/www/html/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\Inventory\Model\SourceItem\Command\SourceItemsSave\Interceptor->Magento\Framework\Interception\{closure}(Array)
#16 /var/www/html/msi/generated/code/Magento/Inventory/Model/SourceItem/Command/SourceItemsSave/Interceptor.php(26): Magento\Inventory\Model\SourceItem\Command\SourceItemsSave\Interceptor->___callPlugins('execute', Array, Array)
#17 /var/www/html/msi/app/code/Magento/InventoryApi/Test/_files/source_items.php(83): Magento\Inventory\Model\SourceItem\Command\SourceItemsSave\Interceptor->execute(Array)
#18 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(173): require('/var/www/html/m...')
#19 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(203): Magento\TestFramework\Annotation\DataFixture->_applyOneFixture('/var/www/html/m...')
#20 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(91): Magento\TestFramework\Annotation\DataFixture->_applyFixtures(Array)
#21 [internal function]: Magento\TestFramework\Annotation\DataFixture->startTransaction(Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#22 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#23 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(96): Magento\TestFramework\EventManager->fireEvent('startTransactio...', Array)
#24 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(81): Magento\TestFramework\Event\Transaction->_startTransaction(Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#25 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/Transaction.php(46): Magento\TestFramework\Event\Transaction->_processTransactionRequests('startTest', Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#26 [internal function]: Magento\TestFramework\Event\Transaction->startTest(Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#27 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
#28 /var/www/html/msi/dev/tests/integration/framework/Magento/TestFramework/Event/PhpUnit.php(126): Magento\TestFramework\EventManager->fireEvent('startTest', Array)
#29 /var/www/html/msi/vendor/phpunit/phpunit/src/Framework/TestResult.php(395): Magento\TestFramework\Event\PhpUnit->startTest(Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#30 /var/www/html/msi/vendor/phpunit/phpunit/src/Framework/TestResult.php(637): PHPUnit\Framework\TestResult->startTest(Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#31 /var/www/html/msi/vendor/phpunit/phpunit/src/Framework/TestCase.php(883): PHPUnit\Framework\TestResult->run(Object(Magento\InventorySourceSelectionApi\Test\Api\SourceSelectionServiceTest))
#32 /var/www/html/msi/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#33 /var/www/html/msi/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#34 /var/www/html/msi/vendor/phpunit/phpunit/src/Framework/TestSuite.php(744): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#35 /var/www/html/msi/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(537): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#36 /var/www/html/msi/vendor/phpunit/phpunit/src/TextUI/Command.php(212): PHPUnit\TextUI\TestRunner->doRun(Object(PHPUnit\Framework\TestSuite), Array, true)
#37 /var/www/html/msi/vendor/phpunit/phpunit/src/TextUI/Command.php(141): PHPUnit\TextUI\Command->run(Array, true)
#38 /var/www/html/msi/vendor/phpunit/phpunit/phpunit(53): PHPUnit\TextUI\Command::main()
#39 {main}
```

This issue can be related to #1377

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1388
