### ISSUE TITLE
Incompatibility with Sample Data

### ISSUE THREAD

**Issue by orlangur** [magento/inventory#1438]
### Preconditions

1. PHP 7.1.18
2. MSI fork at 2f6a348a046a5bc64baf7e06657a1488963acf4b
3. Sample Data at https://github.com/magento/magento2-sample-data/commit/b3fd1a7776b7760b0e5196cbcdda4a87d7b5506b

### Steps to reproduce

1. Install vanilla Magento 2 from MSI fork
2. Try installing sample data from `2.3-develop` as described in https://devdocs.magento.com/guides/v2.2/install-gde/install/sample-data-after-clone.html

### Expected result

1. Seamless installation

### Actual result

1. 
```
Module 'Magento_SalesSampleData':
PHP Fatal error:  Uncaught Error: Call to a member function getQuantity() on null in /Users/orlangur/sites/magento23msi/app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php:107
Stack trace:
#0 /Users/orlangur/sites/magento23msi/app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php(151): Magento\InventoryShipping\Model\SourceDeduction\SourceDeductionService->execute(Object(Magento\InventoryShipping\Model\SourceDeduction\Request\SourceDeductionRequest))
#1 /Users/orlangur/sites/magento23msi/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(72): Magento\InventoryShipping\Observer\SourceDeductionProcessor->execute(Object(Magento\Framework\Event\Observer))
#2 /Users/orlangur/sites/magento23msi/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\InventoryShipping\Observer\SourceDeductionProcessor), Object(Magento\Framework\Event\Observer))
#3 /Users/orlangur/sites/magento in /Users/orlangur/sites/magento23msi/app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php on line 107

Fatal error: Uncaught Error: Call to a member function getQuantity() on null in /Users/orlangur/sites/magento23msi/app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php:107
Stack trace:
#0 /Users/orlangur/sites/magento23msi/app/code/Magento/InventoryShipping/Observer/SourceDeductionProcessor.php(151): Magento\InventoryShipping\Model\SourceDeduction\SourceDeductionService->execute(Object(Magento\InventoryShipping\Model\SourceDeduction\Request\SourceDeductionRequest))
#1 /Users/orlangur/sites/magento23msi/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(72): Magento\InventoryShipping\Observer\SourceDeductionProcessor->execute(Object(Magento\Framework\Event\Observer))
#2 /Users/orlangur/sites/magento23msi/lib/internal/Magento/Framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\InventoryShipping\Observer\SourceDeductionProcessor), Object(Magento\Framework\Event\Observer))
#3 /Users/orlangur/sites/magento in /Users/orlangur/sites/magento23msi/app/code/Magento/InventoryShipping/Model/SourceDeduction/SourceDeductionService.php on line 107
```

Some problem with `Magento_SalesSampleData`. After such install next calls of `setup:updgrade` lead to

```
Module 'Magento_SalesSampleData':
Area code not set: Area code must be set before starting a session.
```

**Comment by maghamed** [comment]
should be fixed with #1592
