### ISSUE TITLE
There is no validation for the value of "type" property of the "sales_channels" extension attribute in "save" method of Magento/InventoryApi/Api/StockRepositoryInterface

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1439]
### Preconditions
1. Magento MSI
2. You have the same codes for website, store and storeview as in the table below.

|Web Site|Store|Store View|
|---|---|---|
|Main Website  (Code: base)|Main Website Store  (Code: main_website_store)|Default Store View  (Code: default)|
|Test Website  (Code: additional)|Test Website Store  (Code: test_website_store)|Test Store View  (Code: test)|

### Steps to reproduce
1. Execute
```
#!/usr/bin/env bash

endpoint="http://<CHANGE>/rest"
username="<CHANGE>"
password="<CHANGE>"

# Get Admin Token
admin_token=$(curl -X POST "$endpoint/V1/integration/admin/token" \
-H "Content-Type: application/json" \
-d '{"username":"'"$username"'","password":"'"$password"'"}') && echo $admin_token && admin_token=$(echo $admin_token | tr -d '"')

# Create a Source
source_code_2="txspeqs" && curl -X POST "$endpoint/V1/inventory/sources" \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $admin_token" \
-d '{"source":{"source_code":"'"$source_code_2"'","name":"Texas Sport Equipment Source #017","email":"sales@company.com","contact_name":"Ethan Carter","enabled":true,"description":" Source #17","latitude":29.762778,"longitude":-95.383056,"country_id":"US","region_id":57,"region":"Texas","city":"Houston","postcode":"77010","phone":"(555) 555-5555"}}'

# Create a Stock and save id that was returned to a variable
stock_name_2="Stock 2" && stock_id_2=$(curl -X POST "$endpoint/all/V1/inventory/stocks/" \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $admin_token" \
-d '{"stock":{"name":"'"$stock_name_2"'"}}') && echo $stock_id_2

# Assign recently created source to stock
curl -X POST "$endpoint/all/V1/inventory/stock-source-links/" \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $admin_token" \
-d '{"links":[{"stock_id": "'"$stock_id_2"'","source_code":"'"$source_code_2"'","priority":1}]}'

# Modify the Default Stock. I want to have only one website with code "base" assigned as a sales channel. You will loose all the sales channels after this operation. It is undesired side-effect
stock_id_1="1" && stock_name_1="Default Stock" && curl -X PUT "$endpoint/all/V1/inventory/stocks/$stock_id_1" \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $admin_token" \
-d '{"stock":{"stock_id":"'"$stock_id_1"'","name":"'"$stock_name_1"'","extension_attributes":{"sales_channels":[{"code":"additional","type":"abc"}]}}}'

# Create category
default_category_id=2 && curl -X POST "$endpoint/all/V1/categories" \
 -H "Content-Type: application/json" \
 -H "Authorization: Bearer $admin_token" \
 -d '{"category":{"parent_id":"'"$default_category_id"'","name":"Sport Equipment","is_active":true,"include_in_menu":true,"custom_attributes":[{"attribute_code":"is_anchor","value":"1"},{"attribute_code":"url_key","value":"sports-equipment"},{"attribute_code":"url_path","value":"sports-equipment"}]}}' | json_pp
```

2. Navigate to "<host>/sports-equipment.html"

### Expected result:
1. Category page renders

### Actual result
1. Exception
```
{"0":"No linked stock found","1":"#0 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\InventorySales\\Model\\StockResolver->get('website', 'base')\n#1 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\InventorySales\\Model\\StockResolver\\Interceptor->___callParent('get', Array)\n#2 \/var\/www\/html\/msi-test\/app\/code\/Magento\/InventoryCatalog\/Plugin\/InventorySalesApi\/StockResolver\/AdaptStockResolverToAdminWebsitePlugin.php(61): Magento\\InventorySales\\Model\\StockResolver\\Interceptor->Magento\\Framework\\Interception\\{closure}('website', 'base')\n#3 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(135): Magento\\InventoryCatalog\\Plugin\\InventorySalesApi\\StockResolver\\AdaptStockResolverToAdminWebsitePlugin->aroundGet(Object(Magento\\InventorySales\\Model\\StockResolver\\Interceptor), Object(Closure), 'website', 'base')\n#4 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\InventorySales\\Model\\StockResolver\\Interceptor->Magento\\Framework\\Interception\\{closure}('website', 'base')\n#5 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/InventorySales\/Model\/StockResolver\/Interceptor.php(26): Magento\\InventorySales\\Model\\StockResolver\\Interceptor->___callPlugins('get', Array, NULL)\n#6 \/var\/www\/html\/msi-test\/app\/code\/Magento\/InventoryCatalog\/Model\/GetStockIdForCurrentWebsite.php(48): Magento\\InventorySales\\Model\\StockResolver\\Interceptor->get('website', 'base')\n#7 \/var\/www\/html\/msi-test\/app\/code\/Magento\/InventoryCatalog\/Plugin\/CatalogInventory\/Model\/ResourceModel\/Stock\/Status\/AdaptAddStockDataToCollectionPlugin.php(57): Magento\\InventoryCatalog\\Model\\GetStockIdForCurrentWebsite->execute()\n#8 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(135): Magento\\InventoryCatalog\\Plugin\\CatalogInventory\\Model\\ResourceModel\\Stock\\Status\\AdaptAddStockDataToCollectionPlugin->aroundAddStockDataToCollection(Object(Magento\\CatalogInventory\\Model\\ResourceModel\\Stock\\Status\\Interceptor), Object(Closure), Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor), true)\n#9 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\CatalogInventory\\Model\\ResourceModel\\Stock\\Status\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor), true)\n#10 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/CatalogInventory\/Model\/ResourceModel\/Stock\/Status\/Interceptor.php(104): Magento\\CatalogInventory\\Model\\ResourceModel\\Stock\\Status\\Interceptor->___callPlugins('addStockDataToC...', Array, NULL)\n#11 \/var\/www\/html\/msi-test\/app\/code\/Magento\/CatalogInventory\/Helper\/Stock.php(160): Magento\\CatalogInventory\\Model\\ResourceModel\\Stock\\Status\\Interceptor->addStockDataToCollection(Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor), true)\n#12 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/CatalogInventory\/Helper\/Stock\/Interceptor.php(63): Magento\\CatalogInventory\\Helper\\Stock->addIsInStockFilterToCollection(Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor))\n#13 \/var\/www\/html\/msi-test\/app\/code\/Magento\/CatalogInventory\/Model\/Plugin\/Layer.php(52): Magento\\CatalogInventory\\Helper\\Stock\\Interceptor->addIsInStockFilterToCollection(Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor))\n#14 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(121): Magento\\CatalogInventory\\Model\\Plugin\\Layer->beforePrepareProductCollection(Object(Magento\\Catalog\\Model\\Layer\\Category\\Interceptor), Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor))\n#15 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor))\n#16 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/Catalog\/Model\/Layer\/Category\/Interceptor.php(52): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->___callPlugins('prepareProductC...', Array, Array)\n#17 \/var\/www\/html\/msi-test\/app\/code\/Magento\/Catalog\/Model\/Layer.php(147): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->prepareProductCollection(Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor))\n#18 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/Catalog\/Model\/Layer\/Category\/Interceptor.php(37): Magento\\Catalog\\Model\\Layer->getProductCollection()\n#19 \/var\/www\/html\/msi-test\/app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(459): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->getProductCollection()\n#20 \/var\/www\/html\/msi-test\/app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(116): Magento\\Catalog\\Block\\Product\\ListProduct->initializeProductCollection()\n#21 \/var\/www\/html\/msi-test\/app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(348): Magento\\Catalog\\Block\\Product\\ListProduct->_getProductCollection()\n#22 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/Catalog\/Block\/Product\/ListProduct\/Interceptor.php(154): Magento\\Catalog\\Block\\Product\\ListProduct->getIdentities()\n#23 \/var\/www\/html\/msi-test\/app\/code\/Magento\/PageCache\/Model\/Layout\/LayoutPlugin.php(71): Magento\\Catalog\\Block\\Product\\ListProduct\\Interceptor->getIdentities()\n#24 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(146): Magento\\PageCache\\Model\\Layout\\LayoutPlugin->afterGetOutput(Object(Magento\\Framework\\View\\Layout\\Interceptor), '\\n    <script ty...')\n#25 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#26 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php(494): Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins('getOutput', Array, Array)\n#27 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/View\/Result\/Page.php(257): Magento\\Framework\\View\\Layout\\Interceptor->getOutput()\n#28 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/View\/Result\/Layout.php(170): Magento\\Framework\\View\\Result\\Page->render(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#29 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Framework\\View\\Result\\Layout->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#30 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', Array)\n#31 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#32 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php(130): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', Array, Array)\n#33 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/App\/Http.php(139): Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#34 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#35 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#36 \/var\/www\/html\/msi-test\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#37 {main}","url":"\/rew.html","script_name":"\/index.php"}
```

**Comment by TomashKhamlai** [comment]
Looks like it is related to #1440 however, the way we do it by using Web API may require additional fixes for validation of the "type" property's value in the "sales_channels" extension attribute

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1452
