### ISSUE TITLE
There are no checks that prevent lost of the last association between Stock and Sales Channels when merchant tries to Save the Stock

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1440]
### Preconditions
1. Magento MSI
2. At least one anchor category included in the menu exists.

### Steps to reproduce
1. Navigate to Stores > Settings > Manage Stocks
2. Open the Default Stock
3. Click on 'Default Website' in Websites multi-select while holding `Ctrl` or `⌘` key pressed to unassign it.
4. Save the Stock.
5. Open the Store Front and open the existing Category

### Expected result
1. The category page renders

### Actual result
1. Exception:
```
{"0":"No linked stock found","1":"#0 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\InventorySales\\Model\\StockResolver->get('website', 'base')\n#1 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\InventorySales\\Model\\StockResolver\\Interceptor->___callParent('get', Array)\n#2 \/var\/www\/html\/msi-test\/app\/code\/Magento\/InventoryCatalog\/Plugin\/InventorySalesApi\/StockResolver\/AdaptStockResolverToAdminWebsitePlugin.php(61): Magento\\InventorySales\\Model\\StockResolver\\Interceptor->Magento\\Framework\\Interception\\{closure}('website', 'base')\n#3 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(135): Magento\\InventoryCatalog\\Plugin\\InventorySalesApi\\StockResolver\\AdaptStockResolverToAdminWebsitePlugin->aroundGet(Object(Magento\\InventorySales\\Model\\StockResolver\\Interceptor), Object(Closure), 'website', 'base')\n#4 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\InventorySales\\Model\\StockResolver\\Interceptor->Magento\\Framework\\Interception\\{closure}('website', 'base')\n#5 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/InventorySales\/Model\/StockResolver\/Interceptor.php(26): Magento\\InventorySales\\Model\\StockResolver\\Interceptor->___callPlugins('get', Array, NULL)\n#6 \/var\/www\/html\/msi-test\/app\/code\/Magento\/InventoryCatalog\/Model\/GetStockIdForCurrentWebsite.php(48): Magento\\InventorySales\\Model\\StockResolver\\Interceptor->get('website', 'base')\n#7 \/var\/www\/html\/msi-test\/app\/code\/Magento\/InventoryCatalog\/Plugin\/CatalogInventory\/Model\/ResourceModel\/Stock\/Status\/AdaptAddStockDataToCollectionPlugin.php(57): Magento\\InventoryCatalog\\Model\\GetStockIdForCurrentWebsite->execute()\n#8 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(135): Magento\\InventoryCatalog\\Plugin\\CatalogInventory\\Model\\ResourceModel\\Stock\\Status\\AdaptAddStockDataToCollectionPlugin->aroundAddStockDataToCollection(Object(Magento\\CatalogInventory\\Model\\ResourceModel\\Stock\\Status\\Interceptor), Object(Closure), Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor), true)\n#9 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\CatalogInventory\\Model\\ResourceModel\\Stock\\Status\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor), true)\n#10 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/CatalogInventory\/Model\/ResourceModel\/Stock\/Status\/Interceptor.php(104): Magento\\CatalogInventory\\Model\\ResourceModel\\Stock\\Status\\Interceptor->___callPlugins('addStockDataToC...', Array, NULL)\n#11 \/var\/www\/html\/msi-test\/app\/code\/Magento\/CatalogInventory\/Helper\/Stock.php(160): Magento\\CatalogInventory\\Model\\ResourceModel\\Stock\\Status\\Interceptor->addStockDataToCollection(Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor), true)\n#12 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/CatalogInventory\/Helper\/Stock\/Interceptor.php(63): Magento\\CatalogInventory\\Helper\\Stock->addIsInStockFilterToCollection(Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor))\n#13 \/var\/www\/html\/msi-test\/app\/code\/Magento\/CatalogInventory\/Model\/Plugin\/Layer.php(52): Magento\\CatalogInventory\\Helper\\Stock\\Interceptor->addIsInStockFilterToCollection(Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor))\n#14 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(121): Magento\\CatalogInventory\\Model\\Plugin\\Layer->beforePrepareProductCollection(Object(Magento\\Catalog\\Model\\Layer\\Category\\Interceptor), Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor))\n#15 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor))\n#16 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/Catalog\/Model\/Layer\/Category\/Interceptor.php(52): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->___callPlugins('prepareProductC...', Array, Array)\n#17 \/var\/www\/html\/msi-test\/app\/code\/Magento\/Catalog\/Model\/Layer.php(147): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->prepareProductCollection(Object(Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor))\n#18 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/Catalog\/Model\/Layer\/Category\/Interceptor.php(37): Magento\\Catalog\\Model\\Layer->getProductCollection()\n#19 \/var\/www\/html\/msi-test\/app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(459): Magento\\Catalog\\Model\\Layer\\Category\\Interceptor->getProductCollection()\n#20 \/var\/www\/html\/msi-test\/app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(116): Magento\\Catalog\\Block\\Product\\ListProduct->initializeProductCollection()\n#21 \/var\/www\/html\/msi-test\/app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(348): Magento\\Catalog\\Block\\Product\\ListProduct->_getProductCollection()\n#22 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/Catalog\/Block\/Product\/ListProduct\/Interceptor.php(154): Magento\\Catalog\\Block\\Product\\ListProduct->getIdentities()\n#23 \/var\/www\/html\/msi-test\/app\/code\/Magento\/PageCache\/Model\/Layout\/LayoutPlugin.php(71): Magento\\Catalog\\Block\\Product\\ListProduct\\Interceptor->getIdentities()\n#24 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(146): Magento\\PageCache\\Model\\Layout\\LayoutPlugin->afterGetOutput(Object(Magento\\Framework\\View\\Layout\\Interceptor), '\\n    <script ty...')\n#25 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#26 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php(494): Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins('getOutput', Array, Array)\n#27 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/View\/Result\/Page.php(257): Magento\\Framework\\View\\Layout\\Interceptor->getOutput()\n#28 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/View\/Result\/Layout.php(170): Magento\\Framework\\View\\Result\\Page->render(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#29 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Framework\\View\\Result\\Layout->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#30 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', Array)\n#31 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#32 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php(130): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', Array, Array)\n#33 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/App\/Http.php(139): Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#34 \/var\/www\/html\/msi-test\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#35 \/var\/www\/html\/msi-test\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#36 \/var\/www\/html\/msi-test\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#37 {main}","url":"\/sports-equipment.html","script_name":"\/index.php"}
```

**Comment by naydav** [comment]
https://github.com/magento-engcom/msi/pull/1452
