### ISSUE TITLE
Fatal error if reindex was not triggered after source/stock creation/assignment

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1627]
### Preconditions
Magento MSI

### Steps to reproduce
1. Populate products, stocks, and sources
```
endpoint="http://<CHANGE>/rest"
username="<CHANGE>"
password="<CHANGE>"

# Get Admin Token
admin_token=$(curl -X POST "$endpoint/V1/integration/admin/token" \
-H "Content-Type: application/json" \
-d '{"username":"'"$username"'","password":"'"$password"'"}') && echo $admin_token && admin_token=$(echo $admin_token | tr -d '"')

# Create a category
curl -X POST "$endpoint/V1/categories" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"category":{"parent_id":2,"name":"Category 1","is_active":true,"level":2,"children":"","created_at":"2018-01-01 00:00:01","updated_at":"2018-01-01 00:00:01","path":"1/2/3","available_sort_by":[],"include_in_menu":true,"extension_attributes":{},"custom_attributes":[{"attribute_code":"is_anchor","value":"1"},{"attribute_code":"path","value":"1/2/3"},{"attribute_code":"children_count","value":"0"},{"attribute_code":"url_key","value":"category-1"},{"attribute_code":"url_path","value":"category-1"}]}}' | json_pp

# Create Simple Product
category_id="3"; productSKU="Simple Product SSM 1" && curl -X POST "$endpoint/V1/products" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"product":{"sku":"'"$productSKU"'","name":"'"$productSKU"'","attribute_set_id":4,"price":10,"status":1,"visibility":4,"type_id":"simple","created_at":"2018-01-01 00:00:01","updated_at":"2018-01-01 00:01:00","weight":1,"extension_attributes":{"category_links":[{"position":0,"category_id":"'"$category_id"'"}],"stock_item":{"qty":1000,"is_in_stock":true,"is_qty_decimal":true}}}}' | json_pp

# Create Simple Product
category_id="3"; productSKU="Simple Product SSM 2" && curl -X POST "$endpoint/V1/products" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"product":{"sku":"'"$productSKU"'","name":"'"$productSKU"'","attribute_set_id":4,"price":10,"status":1,"visibility":4,"type_id":"simple","created_at":"2018-01-01 00:00:01","updated_at":"2018-01-01 00:01:00","weight":1,"extension_attributes":{"category_links":[{"position":0,"category_id":"'"$category_id"'"}],"stock_item":{"qty":1000,"is_in_stock":true,"is_qty_decimal":true}}}}' | json_pp

# Create Simple Product
category_id="3"; productSKU="Simple Product SSM 3" && curl -X POST "$endpoint/V1/products" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"product":{"sku":"'"$productSKU"'","name":"'"$productSKU"'","attribute_set_id":4,"price":10,"status":1,"visibility":4,"type_id":"simple","created_at":"2018-01-01 00:00:01","updated_at":"2018-01-01 00:01:00","weight":1,"extension_attributes":{"category_links":[{"position":0,"category_id":"'"$category_id"'"}],"stock_item":{"qty":1000,"is_in_stock":true,"is_qty_decimal":false}}}}' | json_pp

# Create Simple Product
category_id="3"; productSKU="Simple Product SSM 4" && curl -X POST "$endpoint/V1/products" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"product":{"sku":"'"$productSKU"'","name":"'"$productSKU"'","attribute_set_id":4,"price":10,"status":1,"visibility":4,"type_id":"simple","created_at":"2018-01-01 00:00:01","updated_at":"2018-01-01 00:01:00","weight":1,"extension_attributes":{"category_links":[{"position":0,"category_id":"'"$category_id"'"}],"stock_item":{"qty":1000,"is_in_stock":true,"is_qty_decimal":true}}}}' | json_pp

# Create a Source
source_code_2="txspeqs" && curl -X POST "$endpoint/V1/inventory/sources" \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $admin_token" \
-d '{"source":{"source_code":"'"$source_code_2"'","name":"Texas Sport Equipment Source #017","email":"sales@company.com","contact_name":"Ethan Carter","enabled":true,"description":" Source #17","latitude":29.762778,"longitude":-95.383056,"country_id":"US","region_id":57,"region":"Texas","city":"Houston","postcode":"77010","phone":"(555) 555-5555"}}'

# Create a Stock and save id that was returned to a variable
stock_name_2="Stock 2" && stock_id_2=$(curl -X POST "$endpoint/all/V1/inventory/stocks/" \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $admin_token" \
-d '{"stock":{"name":"'"$stock_name_2"'"}}') && echo $stock_id_2
```
2. Manually assign additional source only to additional stock and change the Sales Channel to this Stock
3. Navigate to Category page (if it was cached then try `/category-1.html?a=1`)

### Expected result
Category page opens but it is empty for now. Reindex is required.

### Actual result
You will get a fatal error if reindex won't be performed. Reindex is required.

```
{
    "0": "SQLSTATE[42S02]: Base table or view not found: 1146 Table 'msi.inventory_stock_2' doesn't exist, query was: INSERT INTO `search_tmp_5b978ea6c1d225_16533485` SELECT `main_select`.`entity_id`, SUM(score) AS `relevance` FROM (SELECT DISTINCT  `search_index`.`entity_id`, (((0) + (0)) * 1) AS `score` FROM `catalog_product_index_eav` AS `search_index`
 INNER JOIN `catalog_product_entity` AS `product` ON product.entity_id = search_index.entity_id
 INNER JOIN `inventory_stock_2` AS `stock_index` ON stock_index.sku = product.sku
 INNER JOIN `catalog_category_product_index_store1` AS `category_ids_index` ON search_index.entity_id = category_ids_index.product_id AND category_ids_index.store_id = '1' WHERE (search_index.store_id = '1') AND (`stock_index`.`is_salable` = 1) AND (`search_index`.`attribute_id` = 99 AND `search_index`.`value` in ('2', '4') AND `search_index`.`store_id` = '1') AND (category_ids_index.category_id = 3)) AS `main_select` GROUP BY `entity_id` ORDER BY `relevance` DESC, `entity_id` DESC
 LIMIT 10000",
    "1": "#0 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/DB\/Statement\/Pdo\/Mysql.php(93): Zend_Db_Statement_Pdo->_execute(Array)
#1 \/var\/www\/html\/msi\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Statement.php(303): Magento\\Framework\\DB\\Statement\\Pdo\\Mysql->_execute(Array)
#2 \/var\/www\/html\/msi\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Adapter\/Abstract.php(480): Zend_Db_Statement->execute(Array)
#3 \/var\/www\/html\/msi\/vendor\/magento\/zendframework1\/library\/Zend\/Db\/Adapter\/Pdo\/Abstract.php(238): Zend_Db_Adapter_Abstract->query('INSERT INTO `se...', Array)
#4 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/DB\/Adapter\/Pdo\/Mysql.php(540): Zend_Db_Adapter_Pdo_Abstract->query('INSERT INTO `se...', Array)
#5 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/DB\/Adapter\/Pdo\/Mysql.php(614): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->_query('INSERT INTO `se...', Array)
#6 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Search\/Adapter\/Mysql\/TemporaryStorage.php(110): Magento\\Framework\\DB\\Adapter\\Pdo\\Mysql->query('INSERT INTO `se...')
#7 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Search\/Adapter\/Mysql\/Adapter.php(80): Magento\\Framework\\Search\\Adapter\\Mysql\\TemporaryStorage->storeDocumentsFromSelect(Object(Magento\\Framework\\DB\\Select))
#8 \/var\/www\/html\/msi\/app\/code\/Magento\/Search\/Model\/SearchEngine.php(42): Magento\\Framework\\Search\\Adapter\\Mysql\\Adapter->query(Object(Magento\\Framework\\Search\\Request))
#9 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Search\/Search.php(72): Magento\\Search\\Model\\SearchEngine->search(Object(Magento\\Framework\\Search\\Request))
#10 \/var\/www\/html\/msi\/app\/code\/Magento\/CatalogSearch\/Model\/ResourceModel\/Fulltext\/Collection.php(344): Magento\\Framework\\Search\\Search->search(Object(Magento\\Framework\\Api\\Search\\SearchCriteria))
#11 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Data\/Collection\/AbstractDb.php(341): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection->_renderFiltersBefore()
#12 \/var\/www\/html\/msi\/app\/code\/Magento\/CatalogSearch\/Model\/ResourceModel\/Fulltext\/Collection.php(392): Magento\\Framework\\Data\\Collection\\AbstractDb->_renderFilters()
#13 \/var\/www\/html\/msi\/app\/code\/Magento\/Eav\/Model\/Entity\/Collection\/AbstractCollection.php(919): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection->_renderFilters()
#14 \/var\/www\/html\/msi\/app\/code\/Magento\/Catalog\/Model\/ResourceModel\/Product\/Collection.php(759): Magento\\Eav\\Model\\Entity\\Collection\\AbstractCollection->load(false, false)
#15 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Catalog\\Model\\ResourceModel\\Product\\Collection->load(false, false)
#16 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->___callParent('load', Array)
#17 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->Magento\\Framework\\Interception\\{closure}()
#18 \/var\/www\/html\/msi\/generated\/code\/Magento\/CatalogSearch\/Model\/ResourceModel\/Fulltext\/Collection\/Interceptor.php(325): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->___callPlugins('load', Array, Array)
#19 \/var\/www\/html\/msi\/app\/code\/Magento\/Review\/Observer\/CatalogBlockProductCollectionBeforeToHtmlObserver.php(38): Magento\\CatalogSearch\\Model\\ResourceModel\\Fulltext\\Collection\\Interceptor->load()
#20 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Event\/Invoker\/InvokerDefault.php(72): Magento\\Review\\Observer\\CatalogBlockProductCollectionBeforeToHtmlObserver->execute(Object(Magento\\Framework\\Event\\Observer))
#21 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Event\/Invoker\/InvokerDefault.php(60): Magento\\Framework\\Event\\Invoker\\InvokerDefault->_callObserverMethod(Object(Magento\\Review\\Observer\\CatalogBlockProductCollectionBeforeToHtmlObserver), Object(Magento\\Framework\\Event\\Observer))
#22 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Event\/Manager.php(66): Magento\\Framework\\Event\\Invoker\\InvokerDefault->dispatch(Array, Object(Magento\\Framework\\Event\\Observer))
#23 \/var\/www\/html\/msi\/generated\/code\/Magento\/Framework\/Event\/Manager\/Proxy.php(95): Magento\\Framework\\Event\\Manager->dispatch('catalog_block_p...', Array)
#24 \/var\/www\/html\/msi\/app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(471): Magento\\Framework\\Event\\Manager\\Proxy->dispatch('catalog_block_p...', Array)
#25 \/var\/www\/html\/msi\/app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(116): Magento\\Catalog\\Block\\Product\\ListProduct->initializeProductCollection()
#26 \/var\/www\/html\/msi\/app\/code\/Magento\/Catalog\/Block\/Product\/ListProduct.php(348): Magento\\Catalog\\Block\\Product\\ListProduct->_getProductCollection()
#27 \/var\/www\/html\/msi\/generated\/code\/Magento\/Catalog\/Block\/Product\/ListProduct\/Interceptor.php(154): Magento\\Catalog\\Block\\Product\\ListProduct->getIdentities()
#28 \/var\/www\/html\/msi\/app\/code\/Magento\/PageCache\/Model\/Layout\/LayoutPlugin.php(71): Magento\\Catalog\\Block\\Product\\ListProduct\\Interceptor->getIdentities()
#29 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(146): Magento\\PageCache\\Model\\Layout\\LayoutPlugin->afterGetOutput(Object(Magento\\Framework\\View\\Layout\\Interceptor), '\
    <script ty...')
#30 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Layout\\Interceptor->Magento\\Framework\\Interception\\{closure}()
#31 \/var\/www\/html\/msi\/generated\/code\/Magento\/Framework\/View\/Layout\/Interceptor.php(494): Magento\\Framework\\View\\Layout\\Interceptor->___callPlugins('getOutput', Array, Array)
#32 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/View\/Result\/Page.php(257): Magento\\Framework\\View\\Layout\\Interceptor->getOutput()
#33 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/View\/Result\/Layout.php(170): Magento\\Framework\\View\\Result\\Page->render(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))
#34 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Framework\\View\\Result\\Layout->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))
#35 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', Array)
#36 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))
#37 \/var\/www\/html\/msi\/generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php(130): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', Array, Array)
#38 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/App\/Http.php(139): Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))
#39 \/var\/www\/html\/msi\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()
#40 \/var\/www\/html\/msi\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()
#41 \/var\/www\/html\/msi\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))
#42 {main}",
    "url": "\/category-1.html",
    "script_name": "\/index.php"
}
```

**Comment by Ctucker9233** [comment]
Is this issue valid for 2.2.8? I just ran into it there.

**Comment by ishakhsuvarov** [comment]
@Ctucker9233 This issue can not apply to 2.2.8 as Inventory package works only with 2.3+

**Comment by ishakhsuvarov** [comment]
Fixed in https://github.com/magento/inventory/pull/2572
