### ISSUE TITLE
Uncaught Fatal Error from SourceDeductionService during Credit Memo creation

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#1703]
### Preconditions
1. Magento Open Source with MSI.

### Steps to reproduce
1. Save some time by executing:
```bash
#!/usr/bin/env bash

endpoint="http://<CHANGE>/rest"
username="<CHANGE>"
password="<CHANGE>"

# Get Admin Token
admin_token=$(curl -X POST "$endpoint/V1/integration/admin/token" \
-H "Content-Type: application/json" \
-d '{"username":"'"$username"'","password":"'"$password"'"}') && echo $admin_token && admin_token=$(echo $admin_token | tr -d '"')

# Create Category
curl -X POST "$endpoint/V1/categories" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"category":{"parent_id":2,"name":"Category 1","is_active":true,"level":2,"path":"1/2/3","available_sort_by":[],"include_in_menu":true,"extension_attributes":{},"custom_attributes":[{"attribute_code":"is_anchor","value":"1"},{"attribute_code":"path","value":"1/2/3"},{"attribute_code":"url_key","value":"category-1"},{"attribute_code":"url_path","value":"category-1"}]}}' | json_pp

# Create Simple Products
category_id="3"; productSKU="Simple Product MSM 1" && curl -X POST "$endpoint/V1/products" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"product":{"sku":"'"$productSKU"'","name":"'"$productSKU"'","attribute_set_id":4,"price":10,"status":1,"visibility":4,"type_id":"simple","weight":1,"extension_attributes":{"website_ids":[1],"stock_item":{"qty":1000,"is_in_stock":true,"is_qty_decimal":false}}}}' | json_pp

# Create Bundle Product
productSKU="Bundle Product 1"; category_id="3" && category_id="3" && curl -X POST "$endpoint/V1/products" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"product":{"sku":"'"$productSKU"'","name":"'"$productSKU"'","type_id":"bundle","price":50,"attribute_set_id":4,"custom_attributes":[{"attribute_code":"price_type","value":1},{"attribute_code":"price_view","value":1}],"extension_attributes":{"category_links":[{"position":0,"category_id":"'"$category_id"'"}],"stock_item":{"is_in_stock":true},"bundle_product_options":[{"title":"test option","type":"checkbox","required":true,"product_links":[{"sku":"Simple Product MSM 1","qty":2,"is_default":false,"price":15,"price_type":0}]}]}}}' | json_pp

# Create Customer
curl -X POST $endpoint/V1/customers \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"customer":{"default_billing":"1","default_shipping":"1","email":"earthworm.jim@gmail.com","firstname":"Jim","lastname":"Earthworm","store_id":1,"website_id":1,"addresses":[{"id":1,"region":{"region_code":"CA","region":"California","region_id":12},"region_id":12,"country_id":"US","street":["6161 West Centinela Avenue"],"company":"Magento","telephone":"555-55-555-55","postcode":"90230","city":"Culver City","firstname":"Jim","lastname":"Earthworm","default_shipping":true,"default_billing":true}],"disable_auto_group_change":0,"extension_attributes":{"is_subscribed":false}},"password":"MetaFrame1"}' | json_pp

# Get $customer_token and become Authorized Customer 
customer_token=$(curl -X POST "$endpoint/V1/integration/customer/token" \
 -H "Content-Type: application/json" \
 -d '{"username":"earthworm.jim@gmail.com","password":"MetaFrame1"}') && echo $customer_token && customer_token=$(echo $customer_token | tr -d '"')

# Create a quote
cart_id=$(curl -X POST "$endpoint/V1/carts/mine" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $customer_token") && echo $cart_id && cart_id=$(echo $cart_id | tr -d '"')

# Add the product to the cart
curl -X POST "$endpoint/V1/carts/mine/items" \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $admin_token" \
-d '{"cartItem":{"sku":"'"$productSKU"'","qty":1,"quote_id":"'"$cart_id"'","product_option":{"extension_attributes":{"bundle_options":[{"option_id":1,"option_qty":2,"option_selections":[1]}]}}}}' | json_pp

# Set the shipping and billing address
curl -X POST $endpoint/V1/carts/mine/shipping-information \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $customer_token" \
-d '{"addressInformation":{"shipping_address":{"region":"California","region_id":12,"region_code":"CA","country_id":"US","street":["6161 West Centinela Avenue"],"postcode":"90230","city":"Culver City","firstname":"Jim","lastname":"Earthworm","email":"earthworm.jim@gmail.com","telephone":"(555) 555-5555"},"billing_address":{"region":"California","region_id":12,"region_code":"CA","country_id":"US","street":["6161 West Centinela Avenue"],"postcode":"90230","city":"Culver City","firstname":"Jim","lastname":"Earthworm","email":"earthworm.jim@gmail.com","telephone":"(555) 555-5555"},"shipping_carrier_code":"flatrate","shipping_method_code":"flatrate"}}' | json_pp

# Submit the payment information
order_id=$(curl -X POST $endpoint/V1/carts/mine/payment-information \
-H "Content-Type: application/json" \
-H "Authorization: Bearer $customer_token" \
-d '{"paymentMethod":{"method":"checkmo"},"billing_address":{"email":"yhiteca@gmail.com","region":"California","region_id":12,"region_code":"CA","country_id":"US","street":["6161 West Centinela Avenue"],"postcode":"90230","city":"Culver City","telephone":"(555) 555-5555","firstname":"Yokoshima","lastname":"Hiteca"}}') && echo $order_id && order_id=$(echo $order_id | tr -d '"')
```
10. Login to backend as Admin and navigate to **Sales > Orders**
11. Open the last order.
12. Create full **Invoice** and full **Shipment**
13. Create a **Credit Memo** with **Return to Stock** option enabled

### Expected result
1. Credit Memo was created
2. Products were returned to stock

### Actual result
1. Error code 500
```
Fatal error: Uncaught Error: Call to a member function getQuantity() on null in /var/www/html/msi/app/code/Magento/InventorySourceDeductionApi/Model/SourceDeductionService.php:85 Stack trace: #0 /var/www/html/msi/app/code/Magento/InventorySales/Model/ReturnProcessor/ProcessRefundItems.php(166): Magento\InventorySourceDeductionApi\Model\SourceDeductionService->execute(Object(Magento\InventorySourceDeductionApi\Model\SourceDeductionRequest)) #1 /var/www/html/msi/app/code/Magento/InventorySales/Plugin/SalesInventory/ProcessReturnQtyOnCreditMemoPlugin.php(93): Magento\InventorySales\Model\ReturnProcessor\ProcessRefundItems->execute(Object(Magento\Sales\Model\Order\Interceptor), Array, Array) #2 /var/www/html/msi/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\InventorySales\Plugin\SalesInventory\ProcessReturnQtyOnCreditMemoPlugin->aroundExecute(Object(Magento\SalesInventory\Model\Order\ReturnProcessor\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Creditmemo\Interceptor), Object(Mage in /var/www/html/msi/app/code/Magento/InventorySourceDeductionApi/Model/SourceDeductionService.php on line 85
```

**Comment by TomashKhamlai** [comment]
Simplified steps as mush as possible.
Credit memo was created on Magento with codebase taken from https://github.com/magento-engcom/magento2ce

**Comment by TomashKhamlai** [comment]
Comparing to #1698, bundle that was created here has no Dinamic Price and Dinamic SKU
