### ISSUE TITLE
Problems with DELETE /V1/inventory/low-quantity-notification

### ISSUE THREAD

**Issue by keharper** [magento/inventory#1724]
### Preconditions

1. Install MSI 2.3-develop

### Steps to reproduce

1. Create a stock and source, and assign a product to a source. Define the quantity available from the source..
2. Define the notify quantity for the product.

```
POST /V1/inventory/low-quantity-notification

{
  "sourceItemConfigurations": [
    {
      "source_code": "reno_wh",
      "notify_stock_qty": 10,
      "sku": "sp2"
    }
  ]
}
```
3. Delete this configuration

```
DELETE /V1/inventory/low-quantity-notification

{
  "sourceCode": "reno_wh",
  "sku": "sp2"
}
```

### Expected result

1. Some indication the configuration was deleted. 

### Actual result

```
{
  "message": "One or more input exceptions have occurred.",
  "errors": [
    {
      "message": "\"%fieldName\" is required. Enter and try again.",
      "parameters": {
        "fieldName": "sourceCode"
      }
    },
    {
      "message": "\"%fieldName\" is required. Enter and try again.",
      "parameters": {
        "fieldName": "sku"
      }
    }
  ],
  "trace": "#0 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php(163): Magento\\Framework\\Webapi\\ServiceInputProcessor->processInputError(Array)\n#1 /Users/keharper/msi/vagrant-magento/magento2ce/app/code/Magento/Webapi/Controller/Rest/InputParamsResolver.php(101): Magento\\Framework\\Webapi\\ServiceInputProcessor->process('Magento\\\\Invento...', 'execute', Array)\n#2 /Users/keharper/msi/vagrant-magento/magento2ce/app/code/Magento/Webapi/Controller/Rest/SynchronousRequestProcessor.php(85): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver->resolve()\n#3 /Users/keharper/msi/vagrant-magento/magento2ce/app/code/Magento/Webapi/Controller/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#4 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#5 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#6 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#7 /Users/keharper/msi/vagrant-magento/magento2ce/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#8 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/App/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#9 /Users/keharper/msi/vagrant-magento/magento2ce/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#10 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#11 /Users/keharper/msi/vagrant-magento/magento2ce/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#12 {main}"
}
```

### Additional issue

Swagger lists the syntax of payload for the DELETE call as follows:

```
{
  "sourceCode": "reno_wh",
  "sku": "sp2"
}
```

The `sourceCode` parameter is listed as `source_code` for `POST /V1/inventory/low-quantity-notification`. The GET /V1/inventory/low-quantity-notification/:sourceCode/:sku call also returns the `source_code` parameter. 

The DELETE call should also list the parameter as `source_code`.

**Comment by maghamed** [comment]
@larsroettig could you please fix Web API Test for DeleteSourceItemConfigurationTest as well
