### ISSUE TITLE
Fix Integration tests on Travis

### ISSUE THREAD

**Issue by maghamed** [magento/inventory#1843]
https://travis-ci.org/magento-engcom/msi/jobs/446122207

```
.....................................................I......FEE 756 / 765 ( 98%)
E..FEEError in fixture: "\/home\/travis\/build\/magento-engcom\/msi\/dev\/tests\/integration\/testsuite\/..\/..\/..\/..\/app\/code\/Magento\/InventoryShipping\/Test\/_files\/products_virtual.php".
 Could not assign product "2358" to websites "594"
 #0 /home/travis/build/magento-engcom/msi/app/code/Magento/InventoryShipping/Test/_files/products_virtual.php(81): Magento\Catalog\Model\ProductWebsiteLinkRepository->save(Object(Magento\Catalog\Model\ProductWebsiteLink))
#1 /home/travis/build/magento-engcom/msi/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(173): require('/home/travis/bu...')
#2 /home/travis/build/magento-engcom/msi/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(203): Magento\TestFramework\Annotation\DataFixture->_applyOneFixture('/home/travis/bu...')
#3 /home/travis/build/magento-engcom/msi/dev/tests/integration/framework/Magento/TestFramework/Annotation/DataFixture.php(59): Magento\TestFramework\Annotation\DataFixture->_applyFixtures(Array)
#4 [internal function]: Magento\TestFramework\Annotation\DataFixture->startTestTransactionRequest(Object(Magento\InventoryShipping\Test\Integration\SourceDeductionForVirtualProductsOnMultiStockTest), Object(Magento\TestFramework\Event\Param\Transaction))
#5 /home/travis/build/magento-engcom/msi/dev/tests/integration/framework/Magento/TestFramework/EventManager.php(49): call_user_func_array(Array, Array)
```

**Comment by bartekszymanski** [comment]
I can't reproduce this issue
