### ISSUE TITLE
Exception is thrown when submitting shipment for a product with custom option

### ISSUE THREAD

**Issue by smoskaluk** [magento/inventory#1850]
### Preconditions

1. Magento MSI single stock mode and multy stock mode
2. Simple product "Product 1" created with some qty and with custom option 
(Input Type: Drop-down, 
Option Title: custom option drop down, 
Required: Yes 
Title: Title Drop-down 1
Price: 2.56
Price Type: Fixed
SKU: sku_drop_down_row_1)

### Steps to reproduce

1. Create order with Simple product "Product 1"  with custom option with qty = 1 from admin
2. Create shipment for this order

### Expected result

1. Shipment created

### Actual result

```
1. Fatal error: Uncaught Error: Call to a member function getQuantity() on null in /var/www/html/vendor/magento/module-inventory-source-deduction-api/Model/SourceDeductionService.php:83 Stack trace: #0 /var/www/html/vendor/magento/module-inventory-shipping/Observer/SourceDeductionProcessor.php(115): Magento\InventorySourceDeductionApi\Model\SourceDeductionService->execute(Object(Magento\InventorySourceDeductionApi\Model\SourceDeductionRequest)) #1 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(72): Magento\InventoryShipping\Observer\SourceDeductionProcessor->execute(Object(Magento\Framework\Event\Observer)) #2 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(60): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Magento\InventoryShipping\Observer\SourceDeductionProcessor), Object(Magento\Framework\Event\Observer)) #3 /var/www/html/vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, O in /var/www/html/vendor/magento/module-inventory-source-deduction-api/Model/SourceDeductionService.php on line 83
```

**Comment by maghamed** [comment]
when fixed, need to provide feedback in the internal Jira ticket - https://jira.corp.magento.com/browse/MAGETWO-95930
