### ISSUE TITLE
POST /V1/inventory/source-selection-algorithm-result payload doesn't accept street_address

### ISSUE THREAD

**Issue by keharper** [magento/inventory#2003]
### Preconditions

1. Branch: MSI 2.3-develop

### Steps to reproduce

1. Configure a source so that it can be used with the distance SSA.
2. Create an order and invoice.
3. Run `POST /V1/inventory/source-selection-algorithm-result` with a payload similar to the following. (The syntax of the payload was taken from Swagger.)

```
{
    "inventoryRequest": {
        "stockId": 2,
        "items": [{
            "sku": "24-WB01",
            "qty": 20
        },
        {
            "sku": "24-WB03",
            "qty": 50
        }],
        "extension_attributes": {
        	"destination_address": {
        		"country": "US",
        		"postcode": "10577",
        		"street_address": "3003 Purchase St",
        		"region": "43",
        		"city": "Purchase"
        	}
        }
    },
    "algorithmCode": "distance"
}
```

### Expected result

1. Success

### Actual result

```
{
    "message": "Missing required argument $streetAddress of Magento\\InventorySourceSelection\\Model\\Address.",
    "trace": "#0 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(34): Magento\\Framework\\ObjectManager\\Factory\\AbstractFactory->resolveArgumentsInRuntime('Magento\\\\Invento...', Array, Array)\n#1 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/ObjectManager/Factory/Dynamic/Developer.php(59): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->_resolveArguments('Magento\\\\Invento...', Array, Array)\n#2 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/ObjectManager/ObjectManager.php(56): Magento\\Framework\\ObjectManager\\Factory\\Dynamic\\Developer->create('Magento\\\\Invento...', Array)\n#3 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php(218): Magento\\Framework\\ObjectManager\\ObjectManager->create('\\\\Magento\\\\Invent...', Array)\n#4 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php(410): Magento\\Framework\\Webapi\\ServiceInputProcessor->_createFromArray('\\\\Magento\\\\Invent...', Array)\n#5 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php(246): Magento\\Framework\\Webapi\\ServiceInputProcessor->convertValue(Array, '\\\\Magento\\\\Invent...')\n#6 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php(410): Magento\\Framework\\Webapi\\ServiceInputProcessor->_createFromArray('\\\\Magento\\\\Invent...', Array)\n#7 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php(246): Magento\\Framework\\Webapi\\ServiceInputProcessor->convertValue(Array, '\\\\Magento\\\\Invent...')\n#8 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php(410): Magento\\Framework\\Webapi\\ServiceInputProcessor->_createFromArray('Magento\\\\Invento...', Array)\n#9 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Webapi/ServiceInputProcessor.php(151): Magento\\Framework\\Webapi\\ServiceInputProcessor->convertValue(Array, 'Magento\\\\Invento...')\n#10 /Users/keharper/msi/vagrant-magento/magento2ce/app/code/Magento/Webapi/Controller/Rest/InputParamsResolver.php(101): Magento\\Framework\\Webapi\\ServiceInputProcessor->process('Magento\\\\Invento...', 'execute', Array)\n#11 /Users/keharper/msi/vagrant-magento/magento2ce/app/code/Magento/Webapi/Controller/Rest/SynchronousRequestProcessor.php(85): Magento\\Webapi\\Controller\\Rest\\InputParamsResolver->resolve()\n#12 /Users/keharper/msi/vagrant-magento/magento2ce/app/code/Magento/Webapi/Controller/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))\n#13 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#14 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent('dispatch', Array)\n#15 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#16 /Users/keharper/msi/vagrant-magento/magento2ce/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins('dispatch', Array, Array)\n#17 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/App/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#18 /Users/keharper/msi/vagrant-magento/magento2ce/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#19 /Users/keharper/msi/vagrant-magento/magento2ce/lib/internal/Magento/Framework/App/Bootstrap.php(257): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#20 /Users/keharper/msi/vagrant-magento/magento2ce/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#21 {main}"
}

```

The call worked fine when I specified `streetAddress` instead of `street_address`

### Recommendations

Either allow `street_address` to be used, or fix the Swagger output so that it states `streetAddress` musr be used.

**Comment by maghamed** [comment]
I think there would be even better to rename `street_address` -> `street` in this case, and the issue will gone
