### ISSUE TITLE
[REST] Unable to create a product without type_id

### ISSUE THREAD

**Issue by RuslanKostiv1** [magento/inventory#2946]
### Preconditions (*)
1. Magento (2.4-develop) with Inventory (1.2-develop) installed.
2. Access token with access to Catalog generated (`System` -> `Integration`) 

### Steps to reproduce (*)

1. Open any REST client
2. Set API request endpoint to `/rest/default/V1/products`
3. Method set to `POST`
4. Headers set to the following:
`Content-Type`: `application/json; charset=UTF-8`
`Accept`: `application/json`
`Authorization`: `Bearer [access_token]`
5. Body 
```
{
    "product": {
        "sku": "sku-test-1",
        "name": "Product_1",
        "attributeSetId": 4
    }
}
```
6. Send request.

### Expected result (*)

1. Simple product successfully created 
2. Response looks like this:
```
{
    "id": 1235,
    "sku": "psku-test-1",
    "name": "Product_1",
    "attribute_set_id": 4,
    "status": 1,
    "visibility": 4,
    "type_id": "simple",
    "created_at": "2020-04-08 22:13:44",
    "updated_at": "2020-04-08 22:13:44",
    "extension_attributes": {
        "website_ids": [
            1
        ]
    },
    "options": [],
    "media_gallery_entries": [],
    "custom_attributes": [
        {
            "attribute_code": "options_container",
            "value": "container2"
        },
        {
            "attribute_code": "url_key",
            "value": "product-1"
        },
        {
            "attribute_code": "required_options",
            "value": "0"
        },
        {
            "attribute_code": "has_options",
            "value": "0"
        },
        {
            "attribute_code": "category_ids",
            "value": []
        }
    ]
}
```

### Actual result (*)
1. Product not created.
2. Response is the following:
```
An error has happened during application run. See exception log for details.

<br />
<b>Fatal error</b>:  Uncaught Exception: User Error: Some transactions have not been committed or rolled back in /var/www/magento2ce/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php on line 3978 in /var/www/magento2ce/lib/internal/Magento/Framework/App/ErrorHandler.php:61
Stack trace:
#0 [internal function]: Magento\Framework\App\ErrorHandler-&gt;handler(256, 'Some transactio...', '/var/www/magent...', 3978, Array)
#1 /var/www/magento2ce/lib/internal/Magento/Framework/DB/Adapter/Pdo/Mysql.php(3978): trigger_error('Some transactio...', 256)
#2 [internal function]: Magento\Framework\DB\Adapter\Pdo\Mysql-&gt;__destruct()
#3 {main}
  thrown in 
<b>/var/www/magento2ce/lib/internal/Magento/Framework/App/ErrorHandler.php</b> on line 
<b>61</b>
<br />
```
3. Log contains the following error
```
...
[2020-04-08 19:55:21] main.CRITICAL: TypeError: Argument 3 passed to Magento\InventoryBundleProduct\Plugin\InventoryConfigurationApi\IsSourceItemManagementAllowedForProductType\DisableBundleTypePlugin::aroundExecute() must be of the type string, null given, called in /var/www/magento2ce/lib/internal/Magento/Framework/Interception/Interceptor.php on line 135 and defined in /var/www/magento2ce/app/code/Magento/InventoryBundleProduct/Plugin/InventoryConfigurationApi/IsSourceItemManagementAllowedForProductType/DisableBundleTypePlugin.php:25
Stack trace:
#0 /var/www/magento2ce/lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\InventoryBundleProduct\Plugin\InventoryConfigurationApi\IsSourceItemManagementAllowedForProductType\DisableBundleTypePlugin->aroundExecute(Object(Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor), Object(Closure), NULL)
#1 /var/www/magento2ce/lib/internal/Magento/Framework/Interception/Interceptor.php(153): Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor->Magento\Framework\Interception\{closure}(NULL)
#2 /var/www/magento2ce/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php(26): Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor->___callPlugins('execute', Array, Array)
#3 
...
```
4. The root cause of the issue is into method [\Magento\InventoryLowQuantityNotification\Plugin\Catalog\Model\ResourceModel\Product\ProcessDefaultSourceItemConfigurationPlugin::afterSave](https://github.com/magento/inventory/blob/61ab15a70f3b05698e417e5498aed98236c97af7/InventoryLowQuantityNotification/Plugin/Catalog/Model/ResourceModel/Product/ProcessDefaultSourceItemConfigurationPlugin.php#L83)
```
if ($this->isSourceItemManagementAllowedForProductType->execute($product->getTypeId()) 
    === false
    || !$product->getExtensionAttributes()->getStockItem()) {
        return $result;
}
```
Method `$this->isSourceItemManagementAllowedForProductType->execute` accepts only a `string` as first argument. There's no `type_id` in request body, so method call with `null` instead of `string` value leads to critical error. 

Magento 2.4-develop without Inventory modules allows to create a product through WEB-API without setting `type_id`

### Proposed fix/workaround 
Setting default type of product before call of execute method can fix this issue
```
$productTypeId = $product->getTypeId() ?? \Magento\Catalog\Model\Product\Type::DEFAULT_TYPE;
if ($this->isSourceItemManagementAllowedForProductType->execute($productTypeId) === false
    || !$product->getExtensionAttributes()->getStockItem()) {
    return $result;
}
```

**Comment by smoskaluk** [comment]
Hi @RuslanKostiv1 , thanx for your report. May you create PR with proposed solution, please?

**Comment by RuslanKostiv1** [comment]
@smoskaluk created https://github.com/magento/inventory/pull/2950
