### ISSUE TITLE
[TSG] MFTF tests failing because of incorrect source grid behaviour (1.2-develop)

### ISSUE THREAD

**Issue by zakdma** [magento/inventory#2986]
### 1.2-develop

These tests are flaky because of incorrect source grid behaviour
- CacheValidationProductSourceStatusChangeTest
- SimpleProductWithZeroQtyAndInStockStatusOnTestSourceVisibleOnHomePageIfBackordersEnabledOnConfigurationPageTest
- StorefrontPartialInvoiceCreatedForOrderWithConfigurableProductInAdminTest

**Example**
Magento\FunctionalTestingFramework.functional\MSI_Multi_Mode.CacheValidationProductSourceStatusChangeTest
Failed
https://app.hiptest.com/projects/69435/test-plan/folders/911762/scenarios/1642340: Cache validation when Source assigned to product is disabled.

**Link**
http://10.234.197.54:8080/job/Functional-Tests-EE/1574/allure/#categories/c85f32971fd8f90b62fb6e09a7165b62/2c95eb332366b123/

**Screenshots**
- http://prntscr.com/s4ucks
- http://prntscr.com/s4ud0d

**Stacktrace**
```
CSS or XPath element with '//tr[td[contains(.,'test_source_1_5ea1d7a0a32992')]]//input[@data-action='select-row']' was not found.
#0 /var/www/html/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php(1009): Codeception\Module\WebDriver->matchFirstOrFail(Object(Facebook\WebDriver\Remote\RemoteWebDriver), '//tr[td[contain...')
#1 /var/www/html/vendor/codeception/codeception/src/Codeception/Module/WebDriver.php(963): Codeception\Module\WebDriver->_findClickable(Object(Facebook\WebDriver\Remote\RemoteWebDriver), '//tr[td[contain...')
#2 [internal function]: Codeception\Module\WebDriver->click('//tr[td[contain...')
#3 /var/www/html/vendor/codeception/codeception/src/Codeception/Step.php(264): call_user_func_array(Array, Array)
#4 /var/www/html/vendor/codeception/codeception/src/Codeception/Scenario.php(72): Codeception\Step->run(Object(Codeception\Lib\ModuleContainer))
#5 /var/www/html/vendor/magento/magento2-functional-testing-framework/src/Magento/FunctionalTestingFramework/_generated/AcceptanceTesterActions.php(1262): Codeception\Scenario->runStep(Object(Codeception\Step\Action))
#6 /var/www/html/dev/tests/acceptance/tests/functional/Magento/_generated/MSI_Multi_Mode/CacheValidationProductSourceStatusChangeTestCest.php(59): Magento\FunctionalTestingFramework\AcceptanceTester->click('//tr[td[contain...')
#7 [internal function]: Magento\AcceptanceTest\_MSI_Multi_Mode\Backend\CacheValidationProductSourceStatusChangeTestCest->_before(Object(Magento\FunctionalTestingFramework\AcceptanceTester))
#8 /var/www/html/vendor/codeception/codeception/src/Codeception/Lib/Di.php(127): ReflectionMethod->invokeArgs(Object(Magento\AcceptanceTest\_MSI_Multi_Mode\Backend\CacheValidationProductSourceStatusChangeTestCest), Array)
#9 /var/www/html/vendor/codeception/codeception/src/Codeception/Test/Cest.php(138): Codeception\Lib\Di->injectDependencies(Object(Magento\AcceptanceTest\_MSI_Multi_Mode\Backend\CacheValidationProductSourceStatusChangeTestCest), '_before', Array)
#10 /var/www/html/vendor/codeception/codeception/src/Codeception/Test/Cest.php(97): Codeception\Test\Cest->invoke('_before', Array)
#11 /var/www/html/vendor/codeception/codeception/src/Codeception/Test/Cest.php(80): Codeception\Test\Cest->executeHook(Object(Magento\FunctionalTestingFramework\AcceptanceTester), 'before')
#12 /var/www/html/vendor/codeception/codeception/src/Codeception/Test/Test.php(89): Codeception\Test\Cest->test()
#13 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(755): Codeception\Test\Test->run(Object(PHPUnit\Framework\TestResult))
#14 /var/www/html/vendor/codeception/phpunit-wrapper/src/Runner.php(110): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#15 /var/www/html/vendor/codeception/codeception/src/Codeception/SuiteManager.php(157): Codeception\PHPUnit\Runner->doEnhancedRun(Object(Codeception\Suite), Object(PHPUnit\Framework\TestResult), Array)
#16 /var/www/html/vendor/codeception/codeception/src/Codeception/Codecept.php(189): Codeception\SuiteManager->run(Object(Codeception\PHPUnit\Runner), Object(PHPUnit\Framework\TestResult), Array)
#17 /var/www/html/vendor/codeception/codeception/src/Codeception/Codecept.php(158): Codeception\Codecept->runSuite(Array, 'functional', NULL)
#18 /var/www/html/vendor/codeception/codeception/src/Codeception/Command/Run.php(466): Codeception\Codecept->run('functional')
#19 /var/www/html/vendor/codeception/codeception/src/Codeception/Command/Run.php(361): Codeception\Command\Run->runSuites(Array, Array)
#20 /var/www/html/vendor/symfony/console/Command/Command.php(255): Codeception\Command\Run->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/symfony/console/Application.php(1001): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(Codeception\Command\Run), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/vendor/codeception/codeception/src/Codeception/Application.php(108): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/vendor/codeception/codeception/codecept(42): Codeception\Application->run()
#26 {main}
```

**Comment by slavvka** [comment]
Looks like StorefrontPartialInvoiceCreatedForOrderWithConfigurableProductInAdminTest fails due to the timeout of 60 secs and is not related to this issues

**Comment by sidolov** [comment]
@slavvka according to the screenshots and steps that lead to failure it's exactly the same case and it will be resolved on the scope of pull request.

**Comment by slavvka** [comment]
@sidolov make sense. In my case I had it with timeout failure
