### ISSUE TITLE
Export product low stock notifications report not working

### ISSUE THREAD

**Issue by dverkade** [magento/inventory#3093]
### Preconditions
1. Magento 2.3.5-p1
2. MSI / Inventory enabled

### Steps to reproduce
1. Log in to admin panel. Go to Reports > Products >Low Stock
2. Locate "Export To" form, select CSV and click "Export"
3. An error message shows

### Expected result
1. Export will be created and downloaded

### Actual result
1. An error message shows

```
Fatal error: Uncaught Error: Call to a member function getCsvFile() on bool in /domains/magentosite.com/http/vendor/magento/module-inventory-low-quantity-notification-admin-ui/Controller/Adminhtml/Report/ExportLowstockCsv.php:41 Stack trace: 
#0 /domains/magentosite.com/http/vendor/magento/framework/App/Action/Action.php(108): Magento\InventoryLowQuantityNotificationAdminUi\Controller\Adminhtml\Report\ExportLowstockCsv->execute() 
#1 /domains/magentosite.com/http/vendor/magento/module-backend/App/AbstractAction.php(231): Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http)) 
#2 /domains/magentosite.com/http/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch(Object(Magento\Framework\App\Request\Http)) 
#3 /domains/magentosite.com/http/vendor/magento/framework/Interception/Interceptor.php(138): Magento\InventoryLowQuantityNotificationAdminUi\Controller\Adminhtml\Report\ExportLowstockCsv\Interceptor->___callPare in /domains/magentosite.com/http/vendor/magento/module-inventory-low-quantity-notification-admin-ui/Controller/Adminhtml/Report/ExportLowstockCsv.php on line 41
```

**Comment by dverkade** [comment]
This error is caused by the following code

```
        $exportBlock = $this->_view->getLayout()->getChildBlock(
            'adminhtml.block.report.product.inventory.lowstock.grid',
            'grid.export'
        );
```

It's looking for a child object in the following parent: `adminhtml.block.report.product.inventory.lowstock.grid` however that parent is never defaint in any other layout XML file, so it will not be able to find the child block, returning false in the `$exportBlock` variable. The next call will fail because it's expecting `$exportBlock` to be object.

**Comment by mathula2504** [comment]
Still I also face this issue in magento 2.3.5-p1. Can anyone help me?
