### ISSUE TITLE
Cannot invoice orders which contain bundle products comprised of physical and virtual products

### ISSUE THREAD

**Issue by iosos-excel** [magento/inventory#3172]
### Preconditions (*)

1. Magento 2.3.5-p2, 2.4.0
2. Magento Inventory is enabled

### Steps to reproduce (*)

1. In the admin, create a sample physical product (This item has weight)
2. Create a sample virtual product (This item has no weight)
3. Create a sample bundle product
    * Set "Dynamic Price" to "No"
    * In "Bundle Items" add 2 options
        * Assign the sample physical product to option 1
        * Assign the sample virtual product to option 2
![image](https://user-images.githubusercontent.com/51681379/90434407-046b8580-e0d6-11ea-88db-5141f2826fc5.png)

4. In the front-end, add the sample bundle product to cart
5. Check out using any payment method
6. Back in the admin, invoice the sample order

### Expected result (*)

1. Order is successfully invoiced

### Actual result (*)

1. Browser displays a 500 error
2. The order is not invoiced
2. The Apache error log contains the following:
```
PHP Fatal error: Uncaught TypeError: Return value of Magento\InventorySourceSelection\Model\Request\InventoryRequest::getItems() must be of the type array, null returned in /www/vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php:102
Stack trace:
#0 /www/vendor/magento/module-inventory-source-selection-api/Model/Algorithms/Result/GetDefaultSortedSourcesResult.php(97): Magento\InventorySourceSelection\Model\Request\InventoryRequest->getItems()
magento/magento2#1 /www/vendor/magento/module-inventory-source-selection/Model/Algorithms/PriorityBasedAlgorithm.php(73): Magento\InventorySourceSelectionApi\Model\Algorithms\Result\GetDefaultSortedSourcesResult->execute(Object(Magento\InventorySourceSelection\Model\Request\InventoryRequest), Array)
magento/magento2#2 /www/vendor/magento/module-inventory-source-selection-api/Model/SourceSelectionService.php(61) in /www/vendor/magento/module-inventory-source-selection/Model/Request/InventoryRequest.php on line 102
```

**Notice:** Issue is not reproducible on 2.4-develop

### Additional information
* Does not happen if the bundle product contains only virtual products
* Does not happen if the price of the bundle product is set to dynamic

**Comment by ahsan-horani-reviver** [comment]
Is there any update on this issue? I am still facing this issue in Magento 2.3.2 @sdzhepa @magento-engcom-team

**Comment by ahsan-horani-reviver** [comment]
Finally addressed this issue. Solution: https://magento.stackexchange.com/a/324163/21432

**Comment by engcom-November** [comment]
Hello @iosos-excel ,

Thank you for your report and collaboration.

We attempted to reproduce the reported issue in our latest 2.4 development instance, but were unable to replicate it. Please refer to the attached screenshot for your reference.

<img width="1222" height="745" alt="Image" src="https://github.com/user-attachments/assets/8bba41da-c3fc-4999-973b-297bc24abf5c" />

As the issue is not reproducible, we are proceeding with closing this ticket. However, if you are still facing any issues, please don’t hesitate to let us know.

Thank you once again!
