### ISSUE TITLE
Create compensations command error: Call to a member function getEntityId() on bool

### ISSUE THREAD

**Issue by vmartins** [magento/inventory#3177]
### Preconditions (*)

1. Migrated from Magento 1.9.3.8 to Magento 2.4.0
2. Migration caused inventory [inconsistencies](https://devdocs.magento.com/guides/v2.4/inventory/inventory-cli-reference.html)

### Steps to reproduce (*)

1. Upgrade from 1.9.3.8 to 2.4.0
2. Run the command to [create compensations](https://devdocs.magento.com/guides/v2.4/inventory/inventory-cli-reference.html#create-compensations-command)
```bash
$ bin/magento inventory:reservation:list-inconsistencies -r | bin/magento inventory:reservation:create-compensations
```

### Expected result (*)

```
Following reservations were created:
- (...)
```

### Actual result (*)

```
Following reservations were created:
PHP Fatal error:  Uncaught Error: Call to a member function getEntityId() on bool in /path/to/magento/vendor/magento/module-inventory-reservation-cli/Command/Input/GetReservationFromCompensationArgument.php:105
Stack trace:
#0 /path/to/magento/vendor/magento/module-inventory-reservation-cli/Command/CreateCompensations.php(123): Magento\InventoryReservationCli\Command\Input\GetReservationFromCompensationArgument->execute()
#1 /path/to/magento/vendor/symfony/console/Command/Command.php(255): Magento\InventoryReservationCli\Command\CreateCompensations->execute()
#2 /path/to/magento/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run()
#3 /path/to/magento/vendor/magento/framework/Interception/Interceptor.php(138): Magento\InventoryReservationCli\Command\CreateCompensations\Interceptor->___callParent()
#4 /path/to/magento/vendor/magento/framework/Interception/Interce in /path/to/magento/vendor/magento/module-inventory-reservation-cli/Command/Input/GetReservationFromCompensationArgument.php on line 105
```

**Comment by sidolov** [comment]
@vmartins it's a known issue, it was fixed in scope of PR: https://github.com/magento/inventory/pull/3144 and will be available with 2.4.1 release. I'm closing the issue since it's already fixed. Thank you for your report!
