### ISSUE TITLE
Shipment create via API salesShipmentRepositoryV1 throw Fatal error

### ISSUE THREAD

**Issue by milindsingh** [magento/inventory#3193]
### Preconditions (*)

1. Magento 2.3.1 with MSI enabled
2. Single Default Source for Inventory
3. The order created from Admin Panel

### Steps to reproduce (*)

1.  Create an order created from Admin Panel
2. Create Shipment via API:

```json
{
  "entity": {
    "increment_id": "000000003",
    "order_id": 3,
    "items": [
        {
          "sku": "WSH12-32-Red",
          "qty": 1
        }
      ],
    "tracks": [
      {
        "order_id": 3,
        "qty": 1,
        "track_number": "123",
        "title": "Test",
        "carrier_code": "dhl"
      }
    ]  
  }
}
```

### Expected result (*)

1. Shipment is created in Admin

### Actual result (*)

1. Fatal Error on API Response
```json
can't parse JSON.  Raw result:

<br />
<b>Fatal error</b>:  Uncaught TypeError: Argument 1 passed to Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor::execute() must be of the type string, null given, called in /opt/lampp7.2/htdocs/magento/2.3.sample/vendor/magento/module-inventory-sales/Model/GetSkuFromOrderItem.php on line 48 and defined in /opt/lampp7.2/htdocs/magento/2.3.sample/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php:20
Stack trace:
#0 /opt/lampp7.2/htdocs/magento/2.3.sample/vendor/magento/module-inventory-sales/Model/GetSkuFromOrderItem.php(48): Magento\InventoryConfiguration\Model\IsSourceItemManagementAllowedForProductType\Interceptor-&gt;execute(NULL)
magento/inventory#1 /opt/lampp7.2/htdocs/magento/2.3.sample/vendor/magento/module-inventory-shipping/Model/GetItemsToDeductFromShipment.php(75): Magento\InventorySales\Model\GetSkuFromOrderItem-&gt;execute(Object(Magento\Sales\Model\Order\Item\Interceptor))
magento/inventory#2 /opt/lampp7.2/htdocs/magento/2.3.sample/vendor/magento/module- in <b>/opt/lampp7.2/htdocs/magento/2.3.sample/generated/code/Magento/InventoryConfiguration/Model/IsSourceItemManagementAllowedForProductType/Interceptor.php</b> on line <b>20</b><br />
{"messages":{"error":[{"code":500,"message":"Server internal error. See details in report api\/398581820999"}]}}
```

Note: **Works after disabling the MSI modules.**

**Comment by engcom-Delta** [comment]
Hi @milindsingh ,

Thanks for your reporting and collaboration.
We have tried to reproduce the issue in latest 2.4-develop instance and we are not able to reproduce the issue.Kindly refer the attached screenshot.

Steps to reproduce : 

1. Single Default Source for Inventory
2. Create an order created from Admin Panel
3. Create Shipment via API:
Observe user is able to create the shipment.

<img width="653" height="340" alt="Image" src="https://github.com/user-attachments/assets/6b2e9423-b436-4507-97a0-a1a954606985" />

<img width="871" height="197" alt="Image" src="https://github.com/user-attachments/assets/7d294cb9-13ce-4f4e-bb23-28990d74c5d0" />

Can you please re-verify in latest 2.4-develop instance and confirm.
Thanks.

**Comment by engcom-Delta** [comment]
Hello,

This issue is being closed since it has not been updated in a long time. Please feel free to reopen or raise a new ticket if the issue still exists.

Thank You!
