### ISSUE TITLE
Cannot perform delete mass-action when using MSI with EE

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/inventory#873]
### Preconditions
1. Magento in Multistock Mode
2. Magento EE
3. [MySQL1.tar.gz](https://github.com/magento-engcom/msi/files/1907876/MySQL1.tar.gz)

### Steps to reproduce
1. Commit f91fd236729a05053e646457d81a50df0ba8f907 or latest
2. Create products with assigned sources.
3. Open Catalog > Products
4. Delete one or more products from products inventory

You can start debugging from this line https://github.com/magento-engcom/msi/blob/f91fd236729a05053e646457d81a50df0ba8f907/lib/internal/Magento/Framework/EntityManager/EntityManager.php#L135

### Expected result
1. Product is removed

### Actual result
1. There has been an error processing your request
```
{"0":"The \"simple56\" product couldn't be removed.","1":"#0 \/var\/www\/html\/pr\/generated\/code\/Magento\/Catalog\/Model\/ProductRepository\/Interceptor.php(63): Magento\\Catalog\\Model\\ProductRepository->delete(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#1 \/var\/www\/html\/pr\/app\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/MassDelete.php(64): Magento\\Catalog\\Model\\ProductRepository\\Interceptor->delete(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#2 \/var\/www\/html\/pr\/generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/MassDelete\/Interceptor.php(24): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete->execute()\n#3 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/App\/Action\/Action.php(107): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->execute()\n#4 \/var\/www\/html\/pr\/app\/code\/Magento\/Backend\/App\/AbstractAction.php(229): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#5 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Backend\\App\\AbstractAction->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#6 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->___callParent('dispatch', Array)\n#7 \/var\/www\/html\/pr\/app\/code\/Magento\/Backend\/App\/Action\/Plugin\/Authentication.php(143): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#8 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(135): Magento\\Backend\\App\\Action\\Plugin\\Authentication->aroundDispatch(Object(Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor), Object(Closure), Object(Magento\\Framework\\App\\Request\\Http))\n#9 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#10 \/var\/www\/html\/pr\/generated\/code\/Magento\/Catalog\/Controller\/Adminhtml\/Product\/MassDelete\/Interceptor.php(39): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->___callPlugins('dispatch', Array, NULL)\n#11 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/App\/FrontController.php(55): Magento\\Catalog\\Controller\\Adminhtml\\Product\\MassDelete\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#12 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(58): Magento\\Framework\\App\\FrontController->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#13 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(138): Magento\\Framework\\App\\FrontController\\Interceptor->___callParent('dispatch', Array)\n#14 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/Interception\/Interceptor.php(153): Magento\\Framework\\App\\FrontController\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))\n#15 \/var\/www\/html\/pr\/generated\/code\/Magento\/Framework\/App\/FrontController\/Interceptor.php(26): Magento\\Framework\\App\\FrontController\\Interceptor->___callPlugins('dispatch', Array, Array)\n#16 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/App\/Http.php(135): Magento\\Framework\\App\\FrontController\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#17 \/var\/www\/html\/pr\/generated\/code\/Magento\/Framework\/App\/Http\/Interceptor.php(24): Magento\\Framework\\App\\Http->launch()\n#18 \/var\/www\/html\/pr\/lib\/internal\/Magento\/Framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http\\Interceptor->launch()\n#19 \/var\/www\/html\/pr\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))\n#20 {main}","url":"\/admin\/catalog\/product\/massDelete\/key\/6d6bea1e869a3ab8d6214faca71c3042bee5a56e01743b56cd5ce72646b7ecbb\/","script_name":"\/index.php"}
```

**Comment by vrann** [comment]
- Staging appears to be a problem

**Comment by RomaKis** [comment]
Stack trace:

```
Magento/Framework/EntityManager/EntityManager#135
Magento/Staging/Model/Operation/Delete#142
Magento/Staging/Model/Operation/Delete/UpdateIntersectedUpdates#112
Magento/Staging/Model/Operation/Delete/UpdateIntersectedUpdates#163
Magento/Staging/Model/Entity/VersionLoader#66
Magento/Framework/EntityManager/EntityManager#70
```

As it try to load model it comes to 
`Magento/InventoryCatalog/Plugin/CatalogInventory/Helper/Stock/AdaptAssignStatusToProductPlugin#72`

Exception is thrown on `Magento/InventoryCatalog/Model/GetProductIdsBySkus#41` as entity is already deleted.

**Comment by TomashKhamlai** [comment]
#1234 has a better description. It can be the same bug, but I am not sure.
